_target_: uni2ts.model.moirai.MoiraiForecast.load_from_checkpoint
checkpoint_path: "/home/wzj/GitHubProjects/uni2ts/outputs/pretrain/moirai_small_wzj_value_loss/lotsa_v1_weighted/moirai_small/HF_checkpoints/last"
num_samples: 100
patch_size: ???
context_length: ???

